//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Admin
{
    public int Admin_Id { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
}

public partial class Brand
{
    public Brand()
    {
        this.Fashion_Item = new HashSet<Fashion_Item>();
    }

    public int BrandID { get; set; }
    public string BrandName { get; set; }
    public Nullable<int> Fashion_Type_Id { get; set; }

    public virtual Fashion_Type Fashion_Type { get; set; }
    public virtual ICollection<Fashion_Item> Fashion_Item { get; set; }
}

public partial class category
{
    public category()
    {
        this.Fashion_Item = new HashSet<Fashion_Item>();
    }

    public int categoryid { get; set; }
    public string categoryname { get; set; }
    public string categoryhtml { get; set; }

    public virtual ICollection<Fashion_Item> Fashion_Item { get; set; }
}

public partial class Color
{
    public Color()
    {
        this.Fashion_Item = new HashSet<Fashion_Item>();
    }

    public int ColorID { get; set; }
    public string ColorName { get; set; }

    public virtual ICollection<Fashion_Item> Fashion_Item { get; set; }
}

public partial class Fashion_Item
{
    public int Fashion_item_Id { get; set; }
    public string Item_Description { get; set; }
    public string ImageURL { get; set; }
    public Nullable<int> Fashion_Type_Id { get; set; }
    public Nullable<int> ColorId { get; set; }
    public Nullable<int> BrandID { get; set; }
    public Nullable<int> categoryid { get; set; }
    public Nullable<double> Price { get; set; }

    public virtual Brand Brand { get; set; }
    public virtual category category { get; set; }
    public virtual Color Color { get; set; }
    public virtual Fashion_Type Fashion_Type { get; set; }
}

public partial class Fashion_Type
{
    public Fashion_Type()
    {
        this.Brand = new HashSet<Brand>();
        this.Fashion_Item = new HashSet<Fashion_Item>();
    }

    public int Fashion_Type_Id { get; set; }
    public string Fashion_Type_Name { get; set; }

    public virtual ICollection<Brand> Brand { get; set; }
    public virtual ICollection<Fashion_Item> Fashion_Item { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}
